server {
    listen 80;
    server_name admin.gastoobra.com;

    access_log /var/log/nginx/gasto-obra/admin-access.log;
    error_log /var/log/nginx/gasto-obra/admin-error.log;

    root /var/www/gasto-obra/admin;
    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass unix:/run/php/php8.3-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTP_AUTHORIZATION $http_authorization;
    }

    # Deny access to config files
    location ~ config\.php$ {
        deny all;
    }
}
