/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './components/**/*.{js,vue,ts}',
    './layouts/**/*.vue',
    './pages/**/*.vue',
    './app.vue',
    './utils/**/*.{js,ts}',
  ],

  // Tema controlado por clase en <html>
  darkMode: 'class',

  theme: {
    extend: {
      fontFamily: {
        display: ['Space Grotesk', 'system-ui', 'sans-serif'],
        ui: ['Red Hat Display', 'system-ui', 'sans-serif'],
      },
      colors: {
        go: {
          bg:               'var(--go-bg)',
          'bg-elevated':    'var(--go-bg-elevated)',
          surface:          'var(--go-surface)',
          'surface-hover':  'var(--go-surface-hover)',
          'surface-alt':    'var(--go-surface-alt)',
          border:           'var(--go-border)',
          'border-subtle':  'var(--go-border-subtle)',
          primary:          'var(--go-primary)',
          'primary-hover':  'var(--go-primary-hover)',
          'primary-active': 'var(--go-primary-active)',
          'primary-muted':  'var(--go-primary-muted)',
          'primary-on':     'var(--go-primary-on)',
          secondary:        'var(--go-secondary)',
          'secondary-hover':'var(--go-secondary-hover)',
          'secondary-muted':'var(--go-secondary-muted)',
          success:          'var(--go-success)',
          'success-muted':  'var(--go-success-muted)',
          danger:           'var(--go-danger)',
          'danger-muted':   'var(--go-danger-muted)',
          warning:          'var(--go-warning)',
          'warning-muted':  'var(--go-warning-muted)',
          info:             'var(--go-info)',
          'info-muted':     'var(--go-info-muted)',
          text:             'var(--go-text)',
          'text-secondary': 'var(--go-text-secondary)',
          'text-tertiary':  'var(--go-text-tertiary)',
          'text-muted':     'var(--go-text-muted)',
          'text-inverse':   'var(--go-text-inverse)',
          'cat-materiales':   'var(--go-cat-materiales)',
          'cat-herramientas': 'var(--go-cat-herramientas)',
          'cat-transporte':   'var(--go-cat-transporte)',
          'cat-mano-de-obra': 'var(--go-cat-mano-de-obra)',
          'cat-comida':       'var(--go-cat-comida)',
          'cat-otros':        'var(--go-cat-otros)',
          'pay-transferencia':'var(--go-pay-transferencia)',
          'pay-efectivo':     'var(--go-pay-efectivo)',
          'pay-tarjeta':      'var(--go-pay-tarjeta)',
          'pay-mercadopago':  'var(--go-pay-mercadopago)',
        },
      },
      borderRadius: {
        'go-sm': 'var(--go-radius-sm)',
        'go-md': 'var(--go-radius-md)',
        'go-lg': 'var(--go-radius-lg)',
        'go-xl': 'var(--go-radius-xl)',
      },
      boxShadow: {
        'go-sm': 'var(--go-shadow-sm)',
        'go-md': 'var(--go-shadow-md)',
        'go-lg': 'var(--go-shadow-lg)',
      },
    },
  },
  plugins: [],
}
