/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./components/**/*.{js,vue,ts}",
    "./layouts/**/*.vue",
    "./pages/**/*.vue",
    "./plugins/**/*.{js,ts}",
    "./utils/**/*.{js,ts}",
    "./app.vue",
    "./error.vue",
  ],
  theme: {
    extend: {
      colors: {
        'go-bg':            'var(--go-bg)',
        'go-bg-elevated':   'var(--go-bg-elevated)',
        'go-surface':       'var(--go-surface)',
        'go-surface-hover': 'var(--go-surface-hover)',
        'go-surface-alt':   'var(--go-surface-alt)',
        'go-border':        'var(--go-border)',
        'go-border-subtle': 'var(--go-border-subtle)',
        'go-primary':       'var(--go-primary)',
        'go-primary-hover': 'var(--go-primary-hover)',
        'go-primary-active':'var(--go-primary-active)',
        'go-primary-muted': 'var(--go-primary-muted)',
        'go-primary-on':    'var(--go-primary-on)',
        'go-secondary':     'var(--go-secondary)',
        'go-secondary-hover':'var(--go-secondary-hover)',
        'go-secondary-muted':'var(--go-secondary-muted)',
        'go-success':       'var(--go-success)',
        'go-success-muted': 'var(--go-success-muted)',
        'go-danger':        'var(--go-danger)',
        'go-danger-muted':  'var(--go-danger-muted)',
        'go-warning':       'var(--go-warning)',
        'go-warning-muted': 'var(--go-warning-muted)',
        'go-info':          'var(--go-info)',
        'go-info-muted':    'var(--go-info-muted)',
        'go-text':          'var(--go-text)',
        'go-text-secondary':'var(--go-text-secondary)',
        'go-text-tertiary': 'var(--go-text-tertiary)',
        'go-text-muted':    'var(--go-text-muted)',
        'go-text-inverse':  'var(--go-text-inverse)',
        'go-cat-materiales':   'var(--go-cat-materiales)',
        'go-cat-herramientas': 'var(--go-cat-herramientas)',
        'go-cat-transporte':   'var(--go-cat-transporte)',
        'go-cat-mano-de-obra': 'var(--go-cat-mano-de-obra)',
        'go-cat-comida':       'var(--go-cat-comida)',
        'go-cat-otros':        'var(--go-cat-otros)',
        'go-pay-transferencia':'var(--go-pay-transferencia)',
        'go-pay-efectivo':     'var(--go-pay-efectivo)',
        'go-pay-tarjeta':      'var(--go-pay-tarjeta)',
        'go-pay-mercadopago':  'var(--go-pay-mercadopago)',
      },
      fontFamily: {
        display: ['Startup', 'system-ui', 'sans-serif'],
        ui:      ['Red Hat Display', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        'go-sm': 'var(--go-radius-sm)',
        'go-md': 'var(--go-radius-md)',
        'go-lg': 'var(--go-radius-lg)',
        'go-xl': 'var(--go-radius-xl)',
      },
      boxShadow: {
        'go-sm': 'var(--go-shadow-sm)',
        'go-md': 'var(--go-shadow-md)',
        'go-lg': 'var(--go-shadow-lg)',
      },
    },
  },
  plugins: [],
}
